### PR TITLE
Error code and text for receive connection timeout

### LINKED ISSUE #81: When recipient times out, BadCodeError is shown when in reality it is connection time out and not bad code
As reported in #79, when connection times out, the error code is somewhat misleading to the user. We need a different error code and corresponding message to convey the connection timeout to the user.

### PR DESCRIPTION
**Pull request by vu3rdd**
Closes #81 

---

## Code Review Checklist (to be filled out by reviewer)

- [x] Description accurately reflects what changes are being made.
- [x] Description explains why the changes are being made (or references an issue containing one).
- [x] The PR appropriately sized.
- [ ] New code has enough tests.
- [x] New code has enough documentation to answer "how do I use it?" and "what does it do?".
- [x] Existing documentation is up-to-date, if impacted.

### CODE REVIEW

**Review by meejah — DISMISSED** [review]
LGTM
(tempted to bikeshed on the wording a bit ..  is "lost" the right word, or could it include not being able to connect at all? my typescript isn't up to finding that out myself immediately ;)

Maybe "Failed to connect in X seconds, ask the sender for a new code". Whatever the message, this is better (distinguishing "bad code" from "network problems").

I don't have much context, but is there a reason this isn't user-initiated? e.g. why is it timing-out programmatically at all (instead of e.g. a "cancel" or "try again" button)? What if we have a very patient user (on very bad networks) :)

**Comment by vu3rdd** [comment]
Thanks Meejah. Totally agree that this should be user initiated. The client shouldn't automatically time out.. 

I also don't really know why such a timeout exists in the recipient side. AFAIK, the protocol itself does not have such a timeout. Also the comment on the code is misleading (https://github.com/LeastAuthority/Transfer/blob/main/src/util.ts#L1). I guess the relay doesn't come into picture here. As we load the recipient URL, these things happen:
1. recipient extracts code from tries to do wormhole messages like `bind`, `claim` etc to the mailbox server..
2. once the mailbox is established, the sender and recipient messages like `offer` happens.
3. only then we start setting up the relay connection

However, this timer starts right at step 1 itself which seems wrong. Also as we discussed, there is a 10 minutes or so timeout set by the mailbox (once the two parties are connected). Ultimately, we will probably get rid of this timeout. For now, I will make it 10 minutes or so in the other PR (#80). 

I will also change the text and update this PR.

**Comment by vu3rdd** [comment]
This is how it appears to the user.

Screenshot from 2022-01-21 16-16-59

**Comment by meejah** [comment]
> there is a 10 minutes or so timeout set by the mailbox (once the two parties are connected).

Just to clarify here: this timer on the mailbox server only starts when _zero_ parties are connected. It resets (and doesn't run at all) if any side is currently connected to that mailbox. That means: mailboxes remain open indefinitely if anyone is connected, and only lose their state if nobody connects to it for >10 minutes.

(This facilitates Dilation where e.g. both parties may happen to be offline at once and cases where neither party is online at the same time, which can work well when there is no bulk/direct connection required .. e.g. I use this for magic-folder invites so might argue that for some deployments making this mailbox timer way longer might be appropriate .. balanced against some attacker wasting resources by keeping a lot of mailboxes open for a long time).

**Review by meejah — APPROVED** [review]

**Review by on-ba — APPROVED** [review]

**Pull request merged**
